// ── Skill Library specs (generated catalog) ───────────────────────────────────
// Compact specs for the 100+ skill library. `catalog.ts` runs each through
// `buildSkill`, which DERIVES tools/touches/writesToVault so every skill passes
// its own Security_Scan by construction (no hand-declared blast radius, no urls /
// "web" / "send external" / secret-looking text in `does` — those trip the scan).
//
// Read-only skills omit `writes`; skills that capture back into the vault set
// `writes: true` (gains the `ingest` tool + vault-write radius). All writes still
// flow through the Aegis proposal gate — nothing mutates the vault directly.

import type { SkillSpec } from './catalog'

export const RESEARCH_SPECS: SkillSpec[] = [
  // ── Research ────────────────────────────────────────────────────────────────
  {
    id: 'literature-review',
    name: 'Literature Review',
    category: 'research',
    icon: 'search',
    accent: '#38bdf8',
    tagline: 'Synthesizes everything your vault knows on a topic into one map.',
    does: 'group the related pages by theme, reconcile agreements and disagreements, and produce a structured cited overview',
    objectiveLabel: 'What topic should I review?',
    objectivePlaceholder: 'e.g. Everything we know about our onboarding funnel',
    exampleOutcomes: ['Themed overview', 'Agreements vs gaps', 'Cited map'],
  },
  {
    id: 'competitor-scan',
    name: 'Competitor Scan',
    category: 'research',
    icon: 'search',
    accent: '#38bdf8',
    tagline: 'Pulls together what your notes say about a rival.',
    does: 'gather every mention of the named competitor, summarize their positioning, strengths, and weaknesses, and note where evidence is thin',
    objectiveLabel: 'Which competitor?',
    objectivePlaceholder: 'e.g. Summarize what we know about Acme Corp',
    exampleOutcomes: ['Positioning summary', 'Strength/weakness list', 'Evidence gaps'],
  },
  {
    id: 'trend-spotter',
    name: 'Trend Spotter',
    category: 'research',
    icon: 'search',
    accent: '#38bdf8',
    tagline: 'Finds patterns building up across your recent notes.',
    does: 'scan recent pages for recurring themes and emerging patterns, then rank them by how much supporting evidence exists',
    objectiveLabel: 'What should I look for trends in?',
    objectivePlaceholder: 'e.g. What themes keep coming up in customer feedback?',
    exampleOutcomes: ['Ranked themes', 'Supporting evidence', 'Early signals'],
  },
  {
    id: 'question-explorer',
    name: 'Question Explorer',
    category: 'research',
    icon: 'search',
    accent: '#38bdf8',
    tagline: 'Breaks a big question into angles and answers each from your vault.',
    does: 'expand the question into sub-questions, answer each one from the vault with citations, and flag the ones the vault cannot yet answer',
    objectiveLabel: 'What question should I explore?',
    objectivePlaceholder: 'e.g. Why are enterprise deals stalling?',
    exampleOutcomes: ['Sub-question answers', 'Cited findings', 'Open questions'],
  },
  {
    id: 'source-comparison',
    name: 'Source Comparison',
    category: 'research',
    icon: 'search',
    accent: '#38bdf8',
    tagline: 'Lays two or more sources side by side and reconciles them.',
    does: 'compare the named sources point by point, highlight where they agree and conflict, and explain which is better supported',
    objectiveLabel: 'Which sources should I compare?',
    objectivePlaceholder: 'e.g. Compare the Q1 and Q2 strategy notes',
    exampleOutcomes: ['Side-by-side table', 'Conflict notes', 'Best-supported view'],
  },
  {
    id: 'fact-checker',
    name: 'Fact Checker',
    category: 'research',
    icon: 'search',
    accent: '#38bdf8',
    tagline: 'Tests a claim against what your vault actually supports.',
    does: 'locate evidence for and against the claim, weigh it, and state whether the vault supports, contradicts, or is silent on it',
    objectiveLabel: 'What claim should I check?',
    objectivePlaceholder: 'e.g. Is it true that churn is highest in month two?',
    exampleOutcomes: ['Verdict', 'Supporting evidence', 'Counter-evidence'],
  },
  {
    id: 'background-briefer',
    name: 'Background Briefer',
    category: 'research',
    icon: 'search',
    accent: '#38bdf8',
    tagline: 'Gets you up to speed on any subject in your vault fast.',
    does: 'assemble a concise primer on the subject from the vault, ordered from fundamentals to current state, with citations',
    objectiveLabel: 'What should I get briefed on?',
    objectivePlaceholder: 'e.g. Brief me on our data retention policy',
    exampleOutcomes: ['Concise primer', 'Key facts', 'Cited sources'],
  },
]

const SALES_SPECS: SkillSpec[] = [
  // ── Sales ─────────────────────────────────────────────────────────────────
  {
    id: 'deal-recap',
    name: 'Deal Recap',
    category: 'sales',
    icon: 'briefcase',
    accent: '#ff7a1f',
    tagline: 'Summarizes the full history of a deal in one read.',
    does: 'gather every note tied to the deal, lay out the timeline, current stage, blockers, and next steps',
    objectiveLabel: 'Which deal?',
    objectivePlaceholder: 'e.g. Recap the Northwind renewal',
    exampleOutcomes: ['Deal timeline', 'Blocker list', 'Next steps'],
  },
  {
    id: 'objection-handler',
    name: 'Objection Handler',
    category: 'sales',
    icon: 'briefcase',
    accent: '#ff7a1f',
    tagline: 'Finds how you have answered an objection before.',
    does: 'search past notes for the objection, summarize the responses that worked, and suggest a tailored reply',
    objectiveLabel: 'What objection?',
    objectivePlaceholder: 'e.g. How do we handle "too expensive"?',
    exampleOutcomes: ['Past responses', 'What worked', 'Suggested reply'],
  },
  {
    id: 'account-planner',
    name: 'Account Planner',
    category: 'sales',
    icon: 'briefcase',
    accent: '#ff7a1f',
    tagline: 'Turns scattered account notes into a plan.',
    does: 'consolidate everything on the account, map stakeholders and goals, and outline a plan to grow it',
    objectiveLabel: 'Which account?',
    objectivePlaceholder: 'e.g. Build a plan for the Globex account',
    exampleOutcomes: ['Stakeholder map', 'Goals', 'Growth plan'],
  },
  {
    id: 'follow-up-drafter',
    name: 'Follow-up Drafter',
    category: 'sales',
    icon: 'pen-line',
    accent: '#ff7a1f',
    writes: true,
    tagline: 'Drafts a follow-up grounded in the last conversation.',
    does: 'review the latest interaction notes and draft a concise, personalized follow-up that references real details, then capture it',
    objectiveLabel: 'Who is the follow-up for?',
    objectivePlaceholder: 'e.g. Draft a follow-up after the demo with Initech',
    exampleOutcomes: ['Personalized draft', 'Referenced details', 'Saved follow-up'],
  },
  {
    id: 'pipeline-reviewer',
    name: 'Pipeline Reviewer',
    category: 'sales',
    icon: 'activity',
    accent: '#ff7a1f',
    tagline: 'Reviews open deals and flags the ones at risk.',
    does: 'examine the open deals in your notes, rank them by momentum, and flag the ones that look stalled or at risk',
    objectiveLabel: 'What should I review?',
    objectivePlaceholder: 'e.g. Which deals are at risk this quarter?',
    exampleOutcomes: ['Momentum ranking', 'At-risk flags', 'Recommended focus'],
  },
  {
    id: 'champion-tracker',
    name: 'Champion Tracker',
    category: 'sales',
    icon: 'briefcase',
    accent: '#ff7a1f',
    tagline: 'Keeps track of your advocates inside each account.',
    does: 'identify the supporters and decision-makers mentioned across notes, summarize their stance, and flag relationships that have gone quiet',
    objectiveLabel: 'Which account or person?',
    objectivePlaceholder: 'e.g. Who are our champions at Hooli?',
    exampleOutcomes: ['Advocate list', 'Stance summary', 'Quiet relationships'],
  },
  {
    id: 'discovery-summarizer',
    name: 'Discovery Summarizer',
    category: 'sales',
    icon: 'briefcase',
    accent: '#ff7a1f',
    tagline: 'Distills a discovery call into needs and fit.',
    does: 'summarize the discovery notes into the prospect needs, pain points, and how well they match what you offer',
    objectiveLabel: 'Which discovery call?',
    objectivePlaceholder: 'e.g. Summarize discovery with Stark Industries',
    exampleOutcomes: ['Needs summary', 'Pain points', 'Fit assessment'],
  },
]

const PRODUCTIVITY_SPECS: SkillSpec[] = [
  // ── Productivity ────────────────────────────────────────────────────────────
  {
    id: 'daily-briefing',
    name: 'Daily Briefing',
    category: 'productivity',
    icon: 'activity',
    accent: '#34d399',
    schedules: ['manual', 'daily'],
    tagline: 'A morning digest of what changed and what needs you.',
    does: 'review what was captured recently, summarize what changed, and list what needs your attention today',
    objectiveLabel: 'What should the briefing cover?',
    objectivePlaceholder: 'e.g. What should I focus on today?',
    exampleOutcomes: ['What changed', 'Needs-you list', "Today's focus"],
  },
  {
    id: 'weekly-review',
    name: 'Weekly Review',
    category: 'productivity',
    icon: 'activity',
    accent: '#34d399',
    schedules: ['manual', 'weekly'],
    tagline: 'End-of-week synthesis across notes and decisions.',
    does: 'synthesize the week from your notes, decisions, and follow-ups into wins, open threads, and what to carry forward',
    objectiveLabel: 'What week should I review?',
    objectivePlaceholder: 'e.g. Summarize my week and what is still open',
    exampleOutcomes: ['Wins', 'Open threads', 'Carry-forward list'],
  },
  {
    id: 'task-extractor',
    name: 'Task Extractor',
    category: 'productivity',
    icon: 'inbox',
    accent: '#34d399',
    writes: true,
    tagline: 'Pulls action items out of messy notes and captures them.',
    does: 'find the commitments and action items buried in the notes, restate each as a clear task with owner and context, and capture them',
    objectiveLabel: 'What should I extract tasks from?',
    objectivePlaceholder: 'e.g. Pull tasks out of this week of meeting notes',
    exampleOutcomes: ['Clear task list', 'Owners', 'Saved follow-ups'],
  },
  {
    id: 'priority-sorter',
    name: 'Priority Sorter',
    category: 'productivity',
    icon: 'activity',
    accent: '#34d399',
    tagline: 'Ranks your open items by what matters most.',
    does: 'gather the open commitments from your notes and rank them by urgency and impact with a short rationale for each',
    objectiveLabel: 'What should I prioritize?',
    objectivePlaceholder: 'e.g. What are my top priorities right now?',
    exampleOutcomes: ['Ranked list', 'Rationale', 'Quick wins'],
  },
  {
    id: 'meeting-notes-cleaner',
    name: 'Meeting Notes Cleaner',
    category: 'productivity',
    icon: 'pen-line',
    accent: '#34d399',
    writes: true,
    tagline: 'Turns rough meeting notes into a clean record.',
    does: 'restructure the raw notes into decisions, action items, and open questions, then capture the cleaned version',
    objectiveLabel: 'Which notes should I clean up?',
    objectivePlaceholder: 'e.g. Clean up yesterday\'s standup notes',
    exampleOutcomes: ['Decisions', 'Action items', 'Saved clean note'],
  },
  {
    id: 'standup-prep',
    name: 'Standup Prep',
    category: 'productivity',
    icon: 'activity',
    accent: '#34d399',
    schedules: ['manual', 'daily'],
    tagline: 'Builds your standup update from recent activity.',
    does: 'review what you captured since the last standup and draft a tight update of done, doing, and blockers',
    objectiveLabel: 'What should the update cover?',
    objectivePlaceholder: 'e.g. Prep my standup for this morning',
    exampleOutcomes: ['Done', 'Doing', 'Blockers'],
  },
  {
    id: 'commitment-tracker',
    name: 'Commitment Tracker',
    category: 'productivity',
    icon: 'inbox',
    accent: '#34d399',
    tagline: 'Surfaces promises you made and have not closed.',
    does: 'find commitments you made across your notes, check whether each looks resolved, and list the ones still open',
    objectiveLabel: 'What commitments should I track?',
    objectivePlaceholder: 'e.g. What did I promise people this month?',
    exampleOutcomes: ['Open commitments', 'Likely-resolved', 'Who is waiting'],
  },
]

const OPS_SPECS: SkillSpec[] = [
  // ── Operations ────────────────────────────────────────────────────────────
  {
    id: 'risk-radar',
    name: 'Risk Radar',
    category: 'ops',
    icon: 'activity',
    accent: '#a78bfa',
    schedules: ['manual', 'weekly'],
    tagline: 'Scans recent decisions for risks worth a second look.',
    does: 'review recent decisions and notes for risks, single points of failure, and assumptions that may not hold, ranked by severity',
    objectiveLabel: 'What should I scan for risk?',
    objectivePlaceholder: 'e.g. Any risks in our recent launch decisions?',
    exampleOutcomes: ['Ranked risks', 'Shaky assumptions', 'Watch items'],
  },
  {
    id: 'contradiction-finder',
    name: 'Contradiction Finder',
    category: 'ops',
    icon: 'activity',
    accent: '#a78bfa',
    tagline: 'Catches places where your notes disagree with each other.',
    does: 'compare related pages for claims that contradict each other and report each conflict with both sources',
    objectiveLabel: 'Where should I look for contradictions?',
    objectivePlaceholder: 'e.g. Do our pricing notes contradict each other?',
    exampleOutcomes: ['Conflict list', 'Both sources', 'Suggested resolution'],
  },
  {
    id: 'stale-content-auditor',
    name: 'Stale Content Auditor',
    category: 'ops',
    icon: 'activity',
    accent: '#a78bfa',
    schedules: ['manual', 'weekly'],
    tagline: 'Flags pages that look out of date.',
    does: 'identify pages that have not been refreshed recently or are overtaken by newer notes, and list them for review',
    objectiveLabel: 'What should I audit for staleness?',
    objectivePlaceholder: 'e.g. Which process docs are out of date?',
    exampleOutcomes: ['Stale pages', 'Why flagged', 'Refresh priority'],
  },
  {
    id: 'process-mapper',
    name: 'Process Mapper',
    category: 'ops',
    icon: 'activity',
    accent: '#a78bfa',
    tagline: 'Reconstructs how a process works from your notes.',
    does: 'piece together the steps of the named process from the vault, lay them out in order, and flag missing or unclear steps',
    objectiveLabel: 'Which process?',
    objectivePlaceholder: 'e.g. Map our customer onboarding process',
    exampleOutcomes: ['Step-by-step map', 'Gaps', 'Unclear steps'],
  },
  {
    id: 'incident-reviewer',
    name: 'Incident Reviewer',
    category: 'ops',
    icon: 'activity',
    accent: '#a78bfa',
    tagline: 'Builds a calm post-mortem from incident notes.',
    does: 'assemble the timeline of the incident from notes, summarize impact and root cause, and list follow-up actions',
    objectiveLabel: 'Which incident?',
    objectivePlaceholder: 'e.g. Review the outage from last Tuesday',
    exampleOutcomes: ['Timeline', 'Root cause', 'Follow-ups'],
  },
  {
    id: 'decision-logger',
    name: 'Decision Logger',
    category: 'ops',
    icon: 'pen-line',
    accent: '#a78bfa',
    writes: true,
    tagline: 'Captures a decision with its rationale so it is not lost.',
    does: 'restate the decision, the options considered, and the reasoning from the notes, then capture it as a clean decision record',
    objectiveLabel: 'What decision should I log?',
    objectivePlaceholder: 'e.g. Log our choice to delay the v2 launch',
    exampleOutcomes: ['Decision record', 'Options weighed', 'Saved rationale'],
  },
  {
    id: 'dependency-checker',
    name: 'Dependency Checker',
    category: 'ops',
    icon: 'activity',
    accent: '#a78bfa',
    tagline: 'Surfaces what depends on what across your work.',
    does: 'trace the dependencies mentioned across notes, show what is blocked by what, and flag fragile chains',
    objectiveLabel: 'What should I check dependencies for?',
    objectivePlaceholder: 'e.g. What is blocking the migration?',
    exampleOutcomes: ['Dependency chain', 'Blockers', 'Fragile links'],
  },
]

const CONTENT_SPECS: SkillSpec[] = [
  // ── Content ───────────────────────────────────────────────────────────────
  {
    id: 'blog-drafter',
    name: 'Blog Drafter',
    category: 'content',
    icon: 'pen-line',
    accent: '#fb923c',
    tagline: 'Drafts a post grounded only in what you know.',
    does: 'draft a structured post on the topic using only supporting vault material, with citations and a note on anything held back',
    objectiveLabel: 'What should I draft?',
    objectivePlaceholder: 'e.g. Draft a post on lessons from our beta',
    exampleOutcomes: ['Structured draft', 'Citations', 'Honesty notes'],
  },
  {
    id: 'newsletter-builder',
    name: 'Newsletter Builder',
    category: 'content',
    icon: 'pen-line',
    accent: '#fb923c',
    schedules: ['manual', 'weekly'],
    tagline: 'Assembles a newsletter from your recent highlights.',
    does: 'pull the most noteworthy recent items from the vault and arrange them into a short, readable newsletter with citations',
    objectiveLabel: 'What should the newsletter cover?',
    objectivePlaceholder: 'e.g. Build this week\'s team newsletter',
    exampleOutcomes: ['Drafted issue', 'Highlights', 'Citations'],
  },
  {
    id: 'summary-writer',
    name: 'Summary Writer',
    category: 'content',
    icon: 'pen-line',
    accent: '#fb923c',
    tagline: 'Condenses long material into a crisp summary.',
    does: 'condense the referenced pages into a tight summary at the length you ask for, keeping the key points and citations',
    objectiveLabel: 'What should I summarize?',
    objectivePlaceholder: 'e.g. Summarize the Q3 planning docs in one page',
    exampleOutcomes: ['Crisp summary', 'Key points', 'Citations'],
  },
  {
    id: 'faq-generator',
    name: 'FAQ Generator',
    category: 'content',
    icon: 'pen-line',
    accent: '#fb923c',
    tagline: 'Turns your knowledge into clear question-and-answer pairs.',
    does: 'identify the common questions a topic raises and answer each from the vault with citations',
    objectiveLabel: 'What topic needs an FAQ?',
    objectivePlaceholder: 'e.g. Generate an FAQ for our refund policy',
    exampleOutcomes: ['Q&A pairs', 'Cited answers', 'Coverage gaps'],
  },
  {
    id: 'social-repurposer',
    name: 'Social Repurposer',
    category: 'content',
    icon: 'pen-line',
    accent: '#fb923c',
    tagline: 'Reshapes an existing note into short social posts.',
    does: 'take the referenced material and reshape it into a few short posts in your voice, each grounded in the source',
    objectiveLabel: 'What should I repurpose?',
    objectivePlaceholder: 'e.g. Turn our case study into 3 short posts',
    exampleOutcomes: ['Short posts', 'Grounded in source', 'Voice match'],
  },
  {
    id: 'outline-builder',
    name: 'Outline Builder',
    category: 'content',
    icon: 'pen-line',
    accent: '#fb923c',
    tagline: 'Builds a structured outline before you write.',
    does: 'organize what the vault knows on the topic into a logical outline with sections and the supporting points under each',
    objectiveLabel: 'What should I outline?',
    objectivePlaceholder: 'e.g. Outline a talk on our design principles',
    exampleOutcomes: ['Section outline', 'Supporting points', 'Source links'],
  },
  {
    id: 'tone-editor',
    name: 'Tone Editor',
    category: 'content',
    icon: 'pen-line',
    accent: '#fb923c',
    tagline: 'Rewrites a draft to match the voice you want.',
    does: 'rework the referenced draft into the requested tone while keeping every fact grounded in the vault',
    objectiveLabel: 'What should I re-tone?',
    objectivePlaceholder: 'e.g. Make this announcement warmer and shorter',
    exampleOutcomes: ['Re-toned draft', 'Facts intact', 'Before/after notes'],
  },
]

const KNOWLEDGE_SPECS: SkillSpec[] = [
  // ── Knowledge ─────────────────────────────────────────────────────────────
  {
    id: 'knowledge-gaps',
    name: 'Knowledge Gaps',
    category: 'knowledge',
    icon: 'search',
    accent: '#22d3ee',
    schedules: ['manual', 'weekly'],
    tagline: 'Finds thin or uncited areas worth filling in.',
    does: 'look across the vault for topics that are thin, uncited, or only partially covered, and suggest what to capture next',
    objectiveLabel: 'Where should I look for gaps?',
    objectivePlaceholder: 'e.g. What do we barely know about our users?',
    exampleOutcomes: ['Thin areas', 'Uncited claims', 'What to capture'],
  },
  {
    id: 'glossary-builder',
    name: 'Glossary Builder',
    category: 'knowledge',
    icon: 'pen-line',
    accent: '#22d3ee',
    writes: true,
    tagline: 'Builds a glossary of the terms your vault uses.',
    does: 'collect the recurring terms and acronyms across the vault, define each from how it is actually used, and capture a glossary',
    objectiveLabel: 'What should the glossary cover?',
    objectivePlaceholder: 'e.g. Build a glossary of our internal terms',
    exampleOutcomes: ['Defined terms', 'Usage examples', 'Saved glossary'],
  },
  {
    id: 'concept-explainer',
    name: 'Concept Explainer',
    category: 'knowledge',
    icon: 'search',
    accent: '#22d3ee',
    tagline: 'Explains a concept the way your own notes describe it.',
    does: 'explain the concept clearly using how the vault describes it, from simple to detailed, with citations',
    objectiveLabel: 'What concept should I explain?',
    objectivePlaceholder: 'e.g. Explain how our credit system works',
    exampleOutcomes: ['Plain explanation', 'Detailed version', 'Citations'],
  },
  {
    id: 'connection-finder',
    name: 'Connection Finder',
    category: 'knowledge',
    icon: 'search',
    accent: '#22d3ee',
    tagline: 'Surfaces non-obvious links between your notes.',
    does: 'find pages that relate to the topic in non-obvious ways and explain how each connects',
    objectiveLabel: 'What should I find connections for?',
    objectivePlaceholder: 'e.g. What connects to our retention work?',
    exampleOutcomes: ['Related pages', 'How they link', 'Surprising ties'],
  },
  {
    id: 'timeline-builder',
    name: 'Timeline Builder',
    category: 'knowledge',
    icon: 'activity',
    accent: '#22d3ee',
    tagline: 'Reconstructs how something unfolded over time.',
    does: 'order the relevant events from the vault into a clear chronological timeline with citations',
    objectiveLabel: 'What should I build a timeline of?',
    objectivePlaceholder: 'e.g. Timeline of how the partnership evolved',
    exampleOutcomes: ['Chronological timeline', 'Key turning points', 'Citations'],
  },
  {
    id: 'entity-profiler',
    name: 'Entity Profiler',
    category: 'knowledge',
    icon: 'search',
    accent: '#22d3ee',
    tagline: 'Builds a one-page profile of any thing in your vault.',
    does: 'gather everything the vault knows about the named entity and assemble a single profile page with citations',
    objectiveLabel: 'What entity should I profile?',
    objectivePlaceholder: 'e.g. Profile our partner Acme',
    exampleOutcomes: ['Profile page', 'Key facts', 'Citations'],
  },
  {
    id: 'duplicate-detector',
    name: 'Duplicate Detector',
    category: 'knowledge',
    icon: 'search',
    accent: '#22d3ee',
    tagline: 'Spots pages that overlap and could be merged.',
    does: 'find pages covering the same ground, explain the overlap, and suggest which to merge or keep',
    objectiveLabel: 'Where should I look for duplicates?',
    objectivePlaceholder: 'e.g. Any overlapping notes on pricing?',
    exampleOutcomes: ['Overlapping pages', 'Merge suggestions', 'Keep/retire'],
  },
]

const PLANNING_SPECS: SkillSpec[] = [
  // ── Planning ──────────────────────────────────────────────────────────────
  {
    id: 'project-tracker',
    name: 'Project Tracker',
    category: 'planning',
    icon: 'activity',
    accent: '#60a5fa',
    tagline: 'Pulls a project into one status view.',
    does: 'gather everything on the project, lay out current status, milestones, open threads, and what is next',
    objectiveLabel: 'Which project?',
    objectivePlaceholder: 'e.g. Status of the website redesign',
    exampleOutcomes: ['Status view', 'Milestones', 'Open threads'],
  },
  {
    id: 'goal-breakdown',
    name: 'Goal Breakdown',
    category: 'planning',
    icon: 'activity',
    accent: '#60a5fa',
    tagline: 'Turns a big goal into concrete steps from what you know.',
    does: 'break the goal into milestones and steps informed by relevant vault context, and flag the unknowns',
    objectiveLabel: 'What goal should I break down?',
    objectivePlaceholder: 'e.g. Break down launching in a new market',
    exampleOutcomes: ['Milestones', 'Concrete steps', 'Unknowns'],
  },
  {
    id: 'roadmap-summarizer',
    name: 'Roadmap Summarizer',
    category: 'planning',
    icon: 'activity',
    accent: '#60a5fa',
    tagline: 'Reads scattered plans into one roadmap view.',
    does: 'consolidate the planning notes into a single roadmap of what is planned, in order, with the rationale for each item',
    objectiveLabel: 'What should I summarize into a roadmap?',
    objectivePlaceholder: 'e.g. Summarize our product roadmap notes',
    exampleOutcomes: ['Ordered roadmap', 'Rationale', 'Open decisions'],
  },
  {
    id: 'retro-facilitator',
    name: 'Retro Facilitator',
    category: 'planning',
    icon: 'activity',
    accent: '#60a5fa',
    schedules: ['manual', 'weekly'],
    tagline: 'Prepares a retrospective from what actually happened.',
    does: 'review the period in the vault and organize it into what went well, what did not, and what to change',
    objectiveLabel: 'What period should I run a retro on?',
    objectivePlaceholder: 'e.g. Run a retro on the last sprint',
    exampleOutcomes: ['Went well', 'Did not', 'Changes to try'],
  },
  {
    id: 'scenario-planner',
    name: 'Scenario Planner',
    category: 'planning',
    icon: 'activity',
    accent: '#60a5fa',
    tagline: 'Thinks through options using your own context.',
    does: 'lay out the plausible options for the decision, weigh each against vault context, and note the tradeoffs',
    objectiveLabel: 'What decision should I plan scenarios for?',
    objectivePlaceholder: 'e.g. Options for our pricing change',
    exampleOutcomes: ['Options', 'Tradeoffs', 'Lean recommendation'],
  },
  {
    id: 'milestone-checker',
    name: 'Milestone Checker',
    category: 'planning',
    icon: 'activity',
    accent: '#60a5fa',
    tagline: 'Checks progress against the milestones you set.',
    does: 'find the milestones in your notes, assess progress on each from recent activity, and flag the ones slipping',
    objectiveLabel: 'What milestones should I check?',
    objectivePlaceholder: 'e.g. Are we on track for the Q4 milestones?',
    exampleOutcomes: ['Progress per milestone', 'Slipping items', 'On-track items'],
  },
  {
    id: 'capacity-reviewer',
    name: 'Capacity Reviewer',
    category: 'planning',
    icon: 'activity',
    accent: '#60a5fa',
    tagline: 'Reads your commitments to gauge how loaded you are.',
    does: 'tally the active commitments across your notes and summarize where load is concentrated and what could be deferred',
    objectiveLabel: 'What should I review capacity for?',
    objectivePlaceholder: 'e.g. How loaded is the team this month?',
    exampleOutcomes: ['Load summary', 'Hot spots', 'Deferral candidates'],
  },
]

const COMMUNICATION_SPECS: SkillSpec[] = [
  // ── Communication ─────────────────────────────────────────────────────────
  {
    id: 'email-drafter',
    name: 'Email Drafter',
    category: 'communication',
    icon: 'pen-line',
    accent: '#f472b6',
    tagline: 'Drafts an email grounded in real context.',
    does: 'review the relevant history and draft a clear, courteous message that references the real details',
    objectiveLabel: 'What email should I draft?',
    objectivePlaceholder: 'e.g. Draft an update to the client on timing',
    exampleOutcomes: ['Clear draft', 'Referenced details', 'Suggested subject'],
  },
  {
    id: 'update-writer',
    name: 'Status Update Writer',
    category: 'communication',
    icon: 'pen-line',
    accent: '#f472b6',
    schedules: ['manual', 'weekly'],
    tagline: 'Writes a status update from recent activity.',
    does: 'summarize recent progress from the vault into a concise status update of progress, blockers, and next steps',
    objectiveLabel: 'What should the update cover?',
    objectivePlaceholder: 'e.g. Write a status update for stakeholders',
    exampleOutcomes: ['Progress', 'Blockers', 'Next steps'],
  },
  {
    id: 'talking-points',
    name: 'Talking Points',
    category: 'communication',
    icon: 'briefcase',
    accent: '#f472b6',
    tagline: 'Preps the key points before an important conversation.',
    does: 'assemble the most relevant facts and history into a short set of talking points with the supporting detail',
    objectiveLabel: 'What conversation should I prep for?',
    objectivePlaceholder: 'e.g. Talking points for the board update',
    exampleOutcomes: ['Key points', 'Supporting facts', 'Anticipated questions'],
  },
  {
    id: 'announcement-drafter',
    name: 'Announcement Drafter',
    category: 'communication',
    icon: 'pen-line',
    accent: '#f472b6',
    tagline: 'Drafts a clear announcement from the facts.',
    does: 'draft a concise announcement grounded in what the vault confirms, with the what, why, and what changes for the reader',
    objectiveLabel: 'What should I announce?',
    objectivePlaceholder: 'e.g. Draft the announcement for the new policy',
    exampleOutcomes: ['Clear announcement', 'What changes', 'Grounded facts'],
  },
  {
    id: 'reply-suggester',
    name: 'Reply Suggester',
    category: 'communication',
    icon: 'pen-line',
    accent: '#f472b6',
    tagline: 'Suggests a reply informed by past exchanges.',
    does: 'review prior exchanges on the matter and suggest a reply that is consistent with what was said before',
    objectiveLabel: 'What should I reply to?',
    objectivePlaceholder: 'e.g. Suggest a reply about the contract terms',
    exampleOutcomes: ['Suggested reply', 'Consistency notes', 'Tone options'],
  },
  {
    id: 'briefing-pack',
    name: 'Briefing Pack',
    category: 'communication',
    icon: 'briefcase',
    accent: '#f472b6',
    tagline: 'Builds a short pack to bring someone up to speed.',
    does: 'pull the essentials on the topic into a short briefing pack a newcomer could read in minutes, with citations',
    objectiveLabel: 'What should the briefing pack cover?',
    objectivePlaceholder: 'e.g. Briefing pack on the partnership for a new hire',
    exampleOutcomes: ['Short pack', 'Essentials', 'Citations'],
  },
  {
    id: 'tone-check',
    name: 'Message Tone Check',
    category: 'communication',
    icon: 'pen-line',
    accent: '#f472b6',
    tagline: 'Reviews a draft for clarity and tone before you send.',
    does: 'review the referenced draft for clarity, tone, and anything that reads as unclear or abrupt, and suggest fixes',
    objectiveLabel: 'What draft should I check?',
    objectivePlaceholder: 'e.g. Check the tone of this customer reply',
    exampleOutcomes: ['Clarity notes', 'Tone flags', 'Suggested fixes'],
  },
]

const FINANCE_SPECS: SkillSpec[] = [
  // ── Finance ───────────────────────────────────────────────────────────────
  {
    id: 'spend-reviewer',
    name: 'Spend Reviewer',
    category: 'finance',
    icon: 'activity',
    accent: '#4ade80',
    tagline: 'Reviews what your notes say about spending.',
    does: 'gather the spending mentioned across notes, group it, and summarize where money is going and what stands out',
    objectiveLabel: 'What spend should I review?',
    objectivePlaceholder: 'e.g. Review our tooling spend this quarter',
    exampleOutcomes: ['Spend summary', 'Notable items', 'Questions to ask'],
  },
  {
    id: 'budget-summarizer',
    name: 'Budget Summarizer',
    category: 'finance',
    icon: 'activity',
    accent: '#4ade80',
    tagline: 'Turns scattered budget notes into one picture.',
    does: 'consolidate the budget notes into a single view of planned versus discussed amounts, with the rationale captured',
    objectiveLabel: 'What budget should I summarize?',
    objectivePlaceholder: 'e.g. Summarize the marketing budget discussion',
    exampleOutcomes: ['Budget view', 'Rationale', 'Open items'],
  },
  {
    id: 'invoice-tracker',
    name: 'Invoice Tracker',
    category: 'finance',
    icon: 'inbox',
    accent: '#4ade80',
    tagline: 'Surfaces invoices and payments mentioned in notes.',
    does: 'find the invoices and payment commitments referenced in the vault and list which look outstanding versus settled',
    objectiveLabel: 'What should I track?',
    objectivePlaceholder: 'e.g. Which invoices are still outstanding?',
    exampleOutcomes: ['Outstanding', 'Settled', 'Follow-ups'],
  },
  {
    id: 'cost-comparer',
    name: 'Cost Comparer',
    category: 'finance',
    icon: 'activity',
    accent: '#4ade80',
    tagline: 'Compares options using the costs in your notes.',
    does: 'lay the options side by side using the cost details captured in the vault and summarize the tradeoffs',
    objectiveLabel: 'What costs should I compare?',
    objectivePlaceholder: 'e.g. Compare the two vendor quotes we logged',
    exampleOutcomes: ['Side-by-side costs', 'Tradeoffs', 'Lean recommendation'],
  },
  {
    id: 'renewal-watcher',
    name: 'Renewal Watcher',
    category: 'finance',
    icon: 'activity',
    accent: '#4ade80',
    schedules: ['manual', 'weekly'],
    tagline: 'Flags contracts and renewals coming up in your notes.',
    does: 'scan the vault for contracts and renewal dates mentioned, and list the ones that appear to be approaching',
    objectiveLabel: 'What renewals should I watch?',
    objectivePlaceholder: 'e.g. Any renewals coming up soon?',
    exampleOutcomes: ['Upcoming renewals', 'Owners', 'What to decide'],
  },
  {
    id: 'expense-categorizer',
    name: 'Expense Categorizer',
    category: 'finance',
    icon: 'inbox',
    accent: '#4ade80',
    writes: true,
    tagline: 'Sorts logged expenses into clean categories.',
    does: 'take the expenses referenced in the notes, group them into clear categories with totals, and capture the summary',
    objectiveLabel: 'What expenses should I categorize?',
    objectivePlaceholder: 'e.g. Categorize this month\'s logged expenses',
    exampleOutcomes: ['Categorized totals', 'Outliers', 'Saved summary'],
  },
  {
    id: 'roi-summarizer',
    name: 'ROI Summarizer',
    category: 'finance',
    icon: 'activity',
    accent: '#4ade80',
    tagline: 'Weighs what an effort cost against what it returned.',
    does: 'pull the costs and outcomes of the initiative from the vault and summarize the return with the evidence behind it',
    objectiveLabel: 'What should I summarize ROI for?',
    objectivePlaceholder: 'e.g. Was the conference sponsorship worth it?',
    exampleOutcomes: ['Cost vs return', 'Evidence', 'Confidence note'],
  },
]

const ENGINEERING_SPECS: SkillSpec[] = [
  // ── Engineering ───────────────────────────────────────────────────────────
  {
    id: 'spec-summarizer',
    name: 'Spec Summarizer',
    category: 'engineering',
    icon: 'pen-line',
    accent: '#818cf8',
    tagline: 'Distills a long spec into the essentials.',
    does: 'condense the referenced spec into goals, key decisions, and open questions, keeping citations to the source',
    objectiveLabel: 'Which spec should I summarize?',
    objectivePlaceholder: 'e.g. Summarize the auth redesign spec',
    exampleOutcomes: ['Goals', 'Key decisions', 'Open questions'],
  },
  {
    id: 'design-decision-log',
    name: 'Design Decision Log',
    category: 'engineering',
    icon: 'pen-line',
    accent: '#818cf8',
    writes: true,
    tagline: 'Records a technical decision and why you made it.',
    does: 'restate the technical decision, the alternatives, and the reasoning from the notes, then capture it as a decision record',
    objectiveLabel: 'What decision should I log?',
    objectivePlaceholder: 'e.g. Log why we chose the queue-based approach',
    exampleOutcomes: ['Decision record', 'Alternatives', 'Saved rationale'],
  },
  {
    id: 'bug-pattern-finder',
    name: 'Bug Pattern Finder',
    category: 'engineering',
    icon: 'search',
    accent: '#818cf8',
    tagline: 'Spots recurring issues across your notes.',
    does: 'review the issues recorded in the vault, group them by underlying pattern, and rank by how often they recur',
    objectiveLabel: 'What should I look for patterns in?',
    objectivePlaceholder: 'e.g. What bugs keep coming back?',
    exampleOutcomes: ['Recurring patterns', 'Frequency', 'Likely root areas'],
  },
  {
    id: 'architecture-explainer',
    name: 'Architecture Explainer',
    category: 'engineering',
    icon: 'search',
    accent: '#818cf8',
    tagline: 'Explains how a system fits together from your notes.',
    does: 'assemble how the system is described across the vault into a clear explanation of its parts and how they interact',
    objectiveLabel: 'What system should I explain?',
    objectivePlaceholder: 'e.g. Explain how our sync pipeline works',
    exampleOutcomes: ['Component overview', 'How parts interact', 'Citations'],
  },
  {
    id: 'release-notes-drafter',
    name: 'Release Notes Drafter',
    category: 'engineering',
    icon: 'pen-line',
    accent: '#818cf8',
    tagline: 'Drafts release notes from what shipped.',
    does: 'gather what changed from the notes and draft clear release notes grouped into features, fixes, and known issues',
    objectiveLabel: 'What release should I draft notes for?',
    objectivePlaceholder: 'e.g. Draft release notes for this sprint',
    exampleOutcomes: ['Features', 'Fixes', 'Known issues'],
  },
  {
    id: 'tech-debt-auditor',
    name: 'Tech Debt Auditor',
    category: 'engineering',
    icon: 'activity',
    accent: '#818cf8',
    tagline: 'Surfaces the debt and shortcuts noted along the way.',
    does: 'collect the shortcuts and known debt recorded in the vault, rank by risk, and suggest what to address first',
    objectiveLabel: 'What should I audit for tech debt?',
    objectivePlaceholder: 'e.g. What tech debt have we logged?',
    exampleOutcomes: ['Debt inventory', 'Risk ranking', 'First to fix'],
  },
  {
    id: 'onboarding-guide',
    name: 'Dev Onboarding Guide',
    category: 'engineering',
    icon: 'pen-line',
    accent: '#818cf8',
    tagline: 'Builds a getting-started guide from your docs.',
    does: 'assemble the setup and context a new engineer needs from the vault into an ordered getting-started guide with citations',
    objectiveLabel: 'What should the guide cover?',
    objectivePlaceholder: 'e.g. Build an onboarding guide for the backend',
    exampleOutcomes: ['Ordered guide', 'Setup steps', 'Citations'],
  },
]

const MARKETING_SPECS: SkillSpec[] = [
  // ── Marketing ─────────────────────────────────────────────────────────────
  {
    id: 'campaign-recap',
    name: 'Campaign Recap',
    category: 'marketing',
    icon: 'activity',
    accent: '#fb7185',
    tagline: 'Summarizes how a campaign went from your notes.',
    does: 'gather the notes on the campaign, summarize what was done and what resulted, and call out the lessons',
    objectiveLabel: 'Which campaign?',
    objectivePlaceholder: 'e.g. Recap the spring launch campaign',
    exampleOutcomes: ['What was done', 'Results', 'Lessons'],
  },
  {
    id: 'messaging-auditor',
    name: 'Messaging Auditor',
    category: 'marketing',
    icon: 'search',
    accent: '#fb7185',
    tagline: 'Checks whether your messaging stays consistent.',
    does: 'compare how the product or value is described across notes and flag where the messaging drifts or conflicts',
    objectiveLabel: 'What messaging should I audit?',
    objectivePlaceholder: 'e.g. Is our value prop consistent everywhere?',
    exampleOutcomes: ['Consistency check', 'Drift flags', 'Suggested wording'],
  },
  {
    id: 'persona-builder',
    name: 'Persona Builder',
    category: 'marketing',
    icon: 'search',
    accent: '#fb7185',
    writes: true,
    tagline: 'Builds an audience persona from real signals.',
    does: 'synthesize what the vault knows about the audience into a grounded persona of needs, goals, and objections, then capture it',
    objectiveLabel: 'What persona should I build?',
    objectivePlaceholder: 'e.g. Build a persona for our power users',
    exampleOutcomes: ['Grounded persona', 'Needs & goals', 'Saved profile'],
  },
  {
    id: 'positioning-helper',
    name: 'Positioning Helper',
    category: 'marketing',
    icon: 'briefcase',
    accent: '#fb7185',
    tagline: 'Sharpens how you position against alternatives.',
    does: 'pull what the vault says about your strengths and the alternatives, and draft a clear positioning statement with support',
    objectiveLabel: 'What should I position?',
    objectivePlaceholder: 'e.g. Position us against the cheaper option',
    exampleOutcomes: ['Positioning statement', 'Differentiators', 'Support'],
  },
  {
    id: 'content-calendar',
    name: 'Content Calendar',
    category: 'marketing',
    icon: 'activity',
    accent: '#fb7185',
    writes: true,
    tagline: 'Plans content themes from what you already know.',
    does: 'turn the topics the vault is rich in into a sequenced set of content ideas with the angle for each, then capture the plan',
    objectiveLabel: 'What should the calendar cover?',
    objectivePlaceholder: 'e.g. Plan a month of content from our research',
    exampleOutcomes: ['Sequenced ideas', 'Angles', 'Saved plan'],
  },
  {
    id: 'testimonial-finder',
    name: 'Testimonial Finder',
    category: 'marketing',
    icon: 'search',
    accent: '#fb7185',
    tagline: 'Surfaces quotable praise buried in your notes.',
    does: 'find positive feedback and quotable moments recorded in the vault and list each with its source for review',
    objectiveLabel: 'What should I find testimonials for?',
    objectivePlaceholder: 'e.g. Find quotable customer praise',
    exampleOutcomes: ['Quotable moments', 'Sources', 'Usage notes'],
  },
  {
    id: 'launch-checklist',
    name: 'Launch Checklist',
    category: 'marketing',
    icon: 'inbox',
    accent: '#fb7185',
    tagline: 'Assembles a launch checklist from past launches.',
    does: 'review how past launches were run in the vault and assemble a checklist of the steps that mattered',
    objectiveLabel: 'What launch should I prep?',
    objectivePlaceholder: 'e.g. Build a checklist for the next launch',
    exampleOutcomes: ['Checklist', 'Lessons applied', 'Owners to assign'],
  },
]

const PEOPLE_SPECS: SkillSpec[] = [
  // ── People ────────────────────────────────────────────────────────────────
  {
    id: 'person-dossier',
    name: 'Person Dossier',
    category: 'people',
    icon: 'briefcase',
    accent: '#c084fc',
    tagline: 'Everything your vault knows about a person, on one page.',
    does: 'gather every mention of the person, summarize your history, their context, and open threads, with citations',
    objectiveLabel: 'Who should I profile?',
    objectivePlaceholder: 'e.g. What do we know about Jordan at Acme?',
    exampleOutcomes: ['One-page dossier', 'Shared history', 'Open threads'],
  },
  {
    id: 'one-on-one-prep',
    name: '1:1 Prep',
    category: 'people',
    icon: 'briefcase',
    accent: '#c084fc',
    schedules: ['manual', 'weekly'],
    tagline: 'Preps a one-on-one from recent context.',
    does: 'review recent notes about the person, surface follow-ups from last time, wins to recognize, and topics worth raising',
    objectiveLabel: 'Who is the 1:1 with?',
    objectivePlaceholder: 'e.g. Prep my 1:1 with Sam',
    exampleOutcomes: ['Last follow-ups', 'Wins', 'Topics to raise'],
  },
  {
    id: 'feedback-synthesizer',
    name: 'Feedback Synthesizer',
    category: 'people',
    icon: 'inbox',
    accent: '#c084fc',
    tagline: 'Pulls feedback about someone into clear themes.',
    does: 'collect the feedback recorded about the person, group it into themes, and separate strengths from growth areas',
    objectiveLabel: 'Whose feedback should I synthesize?',
    objectivePlaceholder: 'e.g. Synthesize feedback on Alex this quarter',
    exampleOutcomes: ['Themes', 'Strengths', 'Growth areas'],
  },
  {
    id: 'intro-writer',
    name: 'Intro Writer',
    category: 'people',
    icon: 'pen-line',
    accent: '#c084fc',
    tagline: 'Drafts a warm, accurate introduction between two people.',
    does: 'gather context on both people from the vault and draft a short, accurate introduction explaining why they should connect',
    objectiveLabel: 'Who should I introduce?',
    objectivePlaceholder: 'e.g. Intro between our designer and the new advisor',
    exampleOutcomes: ['Intro draft', 'Why connect', 'Context for each'],
  },
  {
    id: 'relationship-refresher',
    name: 'Relationship Refresher',
    category: 'people',
    icon: 'activity',
    accent: '#c084fc',
    schedules: ['manual', 'weekly'],
    tagline: 'Flags contacts you have not touched base with lately.',
    does: 'scan the people mentioned in your notes and surface valuable relationships that appear to have gone quiet',
    objectiveLabel: 'What relationships should I review?',
    objectivePlaceholder: 'e.g. Who have I lost touch with?',
    exampleOutcomes: ['Quiet relationships', 'Last context', 'Reasons to reconnect'],
  },
  {
    id: 'recognition-finder',
    name: 'Recognition Finder',
    category: 'people',
    icon: 'search',
    accent: '#c084fc',
    tagline: 'Surfaces good work worth calling out.',
    does: 'review recent notes for contributions and wins by others that deserve recognition, with the supporting detail',
    objectiveLabel: 'What should I find recognition for?',
    objectivePlaceholder: 'e.g. Whose work should I recognize this week?',
    exampleOutcomes: ['Notable contributions', 'Supporting detail', 'Who to thank'],
  },
  {
    id: 'org-context',
    name: 'Org Context Builder',
    category: 'people',
    icon: 'briefcase',
    accent: '#c084fc',
    tagline: 'Maps who does what from your notes.',
    does: 'piece together the roles and responsibilities mentioned across notes into a clear who-does-what for the group',
    objectiveLabel: 'What group should I map?',
    objectivePlaceholder: 'e.g. Who does what on the partner team?',
    exampleOutcomes: ['Role map', 'Responsibilities', 'Unknowns'],
  },
]

const LEGAL_SPECS: SkillSpec[] = [
  // ── Legal ─────────────────────────────────────────────────────────────────
  {
    id: 'contract-summarizer',
    name: 'Contract Summarizer',
    category: 'legal',
    icon: 'pen-line',
    accent: '#94a3b8',
    tagline: 'Distills a contract in your vault into plain terms.',
    does: 'summarize the referenced agreement into plain-language terms, obligations, and dates, citing the source sections',
    objectiveLabel: 'Which contract should I summarize?',
    objectivePlaceholder: 'e.g. Summarize the vendor agreement we logged',
    exampleOutcomes: ['Plain summary', 'Key obligations', 'Important dates'],
  },
  {
    id: 'obligation-tracker',
    name: 'Obligation Tracker',
    category: 'legal',
    icon: 'activity',
    accent: '#94a3b8',
    tagline: 'Lists the commitments your agreements create.',
    does: 'find the obligations and commitments recorded across agreements in the vault and list who owes what, with sources',
    objectiveLabel: 'What obligations should I track?',
    objectivePlaceholder: 'e.g. What are we obligated to deliver?',
    exampleOutcomes: ['Obligation list', 'Owners', 'Source sections'],
  },
  {
    id: 'clause-finder',
    name: 'Clause Finder',
    category: 'legal',
    icon: 'search',
    accent: '#94a3b8',
    tagline: 'Locates how a clause type appears across your docs.',
    does: 'search the agreements in the vault for the named clause type and summarize how each one is worded, with sources',
    objectiveLabel: 'What clause should I find?',
    objectivePlaceholder: 'e.g. Find the termination clauses in our contracts',
    exampleOutcomes: ['Matching clauses', 'How worded', 'Source docs'],
  },
  {
    id: 'policy-explainer',
    name: 'Policy Explainer',
    category: 'legal',
    icon: 'search',
    accent: '#94a3b8',
    tagline: 'Explains a policy the way your docs define it.',
    does: 'explain the policy in plain language using how the vault documents it, with the relevant sections cited',
    objectiveLabel: 'What policy should I explain?',
    objectivePlaceholder: 'e.g. Explain our data retention policy',
    exampleOutcomes: ['Plain explanation', 'What it requires', 'Citations'],
  },
  {
    id: 'compliance-checklist',
    name: 'Compliance Checklist',
    category: 'legal',
    icon: 'inbox',
    accent: '#94a3b8',
    tagline: 'Builds a checklist from the requirements you have noted.',
    does: 'gather the requirements recorded in the vault and turn them into a checklist of what must be in place, with sources',
    objectiveLabel: 'What should the checklist cover?',
    objectivePlaceholder: 'e.g. Build a checklist from our security requirements',
    exampleOutcomes: ['Requirement checklist', 'Sources', 'Open items'],
  },
  {
    id: 'risk-clause-reviewer',
    name: 'Risk Clause Reviewer',
    category: 'legal',
    icon: 'activity',
    accent: '#94a3b8',
    tagline: 'Flags terms in your agreements worth a closer look.',
    does: 'review the agreements in the vault for terms that look one-sided or risky and explain the concern with the source',
    objectiveLabel: 'What should I review for risky terms?',
    objectivePlaceholder: 'e.g. Any risky terms in the new partner contract?',
    exampleOutcomes: ['Flagged terms', 'Why a concern', 'Source sections'],
  },
  {
    id: 'agreement-comparer',
    name: 'Agreement Comparer',
    category: 'legal',
    icon: 'search',
    accent: '#94a3b8',
    tagline: 'Compares two agreements clause by clause.',
    does: 'compare the two referenced agreements section by section and highlight where their terms differ, with sources',
    objectiveLabel: 'Which agreements should I compare?',
    objectivePlaceholder: 'e.g. Compare the old and new vendor terms',
    exampleOutcomes: ['Differences', 'Notable changes', 'Source sections'],
  },
]

const PERSONAL_SPECS: SkillSpec[] = [
  // ── Personal ──────────────────────────────────────────────────────────────
  {
    id: 'journal-reflector',
    name: 'Journal Reflector',
    category: 'personal',
    icon: 'pen-line',
    accent: '#facc15',
    schedules: ['manual', 'weekly'],
    tagline: 'Reflects your own notes back as gentle insight.',
    does: 'review your recent personal notes and reflect back the recurring themes, moods, and small wins, kindly and honestly',
    objectiveLabel: 'What should I reflect on?',
    objectivePlaceholder: 'e.g. What patterns are in my journal this month?',
    exampleOutcomes: ['Recurring themes', 'Small wins', 'Gentle observations'],
  },
  {
    id: 'habit-tracker',
    name: 'Habit Tracker',
    category: 'personal',
    icon: 'activity',
    accent: '#facc15',
    tagline: 'Spots how your habits show up in your notes.',
    does: 'scan your notes for the habit you name, summarize how consistently it appears, and note what helps or gets in the way',
    objectiveLabel: 'What habit should I track?',
    objectivePlaceholder: 'e.g. How consistent has my reading been?',
    exampleOutcomes: ['Consistency view', 'What helps', 'What gets in the way'],
  },
  {
    id: 'goal-checkin',
    name: 'Goal Check-in',
    category: 'personal',
    icon: 'activity',
    accent: '#facc15',
    schedules: ['manual', 'weekly'],
    tagline: 'Checks your personal goals against recent activity.',
    does: 'find your stated goals in the vault and assess progress on each from recent notes, encouragingly and honestly',
    objectiveLabel: 'What goals should I check on?',
    objectivePlaceholder: 'e.g. How am I tracking on my goals this quarter?',
    exampleOutcomes: ['Progress per goal', 'Momentum', 'Next small step'],
  },
  {
    id: 'reading-digest',
    name: 'Reading Digest',
    category: 'personal',
    icon: 'pen-line',
    accent: '#facc15',
    tagline: 'Summarizes the takeaways from what you saved.',
    does: 'gather the reading notes you captured on the topic and distill the key takeaways and quotes worth keeping',
    objectiveLabel: 'What reading should I digest?',
    objectivePlaceholder: 'e.g. Digest what I saved about focus',
    exampleOutcomes: ['Key takeaways', 'Quotes to keep', 'Open threads'],
  },
  {
    id: 'gratitude-collector',
    name: 'Gratitude Collector',
    category: 'personal',
    icon: 'search',
    accent: '#facc15',
    tagline: 'Surfaces the good moments hiding in your notes.',
    does: 'review your recent notes for positive moments and things that went well, and gather them into a short uplifting summary',
    objectiveLabel: 'What period should I look at?',
    objectivePlaceholder: 'e.g. What went well for me this month?',
    exampleOutcomes: ['Good moments', 'Things that went well', 'A kind summary'],
  },
  {
    id: 'idea-incubator',
    name: 'Idea Incubator',
    category: 'personal',
    icon: 'search',
    accent: '#facc15',
    tagline: 'Revisits old ideas worth another look.',
    does: 'find ideas you jotted down earlier that relate to the topic, summarize each, and note which seem worth revisiting',
    objectiveLabel: 'What ideas should I revisit?',
    objectivePlaceholder: 'e.g. What side-project ideas did I have?',
    exampleOutcomes: ['Past ideas', 'Quick summaries', 'Worth revisiting'],
  },
  {
    id: 'decision-helper',
    name: 'Personal Decision Helper',
    category: 'personal',
    icon: 'activity',
    accent: '#facc15',
    tagline: 'Thinks through a personal choice using your own notes.',
    does: 'lay out the options for the choice, weigh each against what your notes reveal about your priorities, and note the tradeoffs',
    objectiveLabel: 'What decision should I think through?',
    objectivePlaceholder: 'e.g. Should I take on the new commitment?',
    exampleOutcomes: ['Options', 'Tradeoffs', 'What aligns with you'],
  },
]

const LEARNING_SPECS: SkillSpec[] = [
  // ── Learning ──────────────────────────────────────────────────────────────
  {
    id: 'study-guide',
    name: 'Study Guide Builder',
    category: 'learning',
    icon: 'pen-line',
    accent: '#2dd4bf',
    writes: true,
    tagline: 'Turns your notes on a topic into a study guide.',
    does: 'organize what the vault holds on the topic into a study guide of core concepts, ordered from basics to advanced, then capture it',
    objectiveLabel: 'What should the study guide cover?',
    objectivePlaceholder: 'e.g. Build a study guide on our domain model',
    exampleOutcomes: ['Ordered concepts', 'Key points', 'Saved guide'],
  },
  {
    id: 'flashcard-maker',
    name: 'Flashcard Maker',
    category: 'learning',
    icon: 'pen-line',
    accent: '#2dd4bf',
    tagline: 'Generates question-and-answer cards from your notes.',
    does: 'turn the key facts on the topic into clear question-and-answer flashcards, each grounded in a vault page',
    objectiveLabel: 'What should I make flashcards on?',
    objectivePlaceholder: 'e.g. Make flashcards on our pricing tiers',
    exampleOutcomes: ['Q&A cards', 'Grounded answers', 'Coverage notes'],
  },
  {
    id: 'concept-quiz',
    name: 'Concept Quiz',
    category: 'learning',
    icon: 'search',
    accent: '#2dd4bf',
    tagline: 'Quizzes you on what your vault contains.',
    does: 'draw a short set of questions from the topic in the vault, with the answer and source for each so you can self-check',
    objectiveLabel: 'What should I be quizzed on?',
    objectivePlaceholder: 'e.g. Quiz me on our onboarding flow',
    exampleOutcomes: ['Quiz questions', 'Answers', 'Sources'],
  },
  {
    id: 'explain-like-im-new',
    name: 'Explain Simply',
    category: 'learning',
    icon: 'search',
    accent: '#2dd4bf',
    tagline: 'Explains a tough topic in the simplest honest terms.',
    does: 'explain the topic as simply as the vault allows, building from a plain-language core up to the details, with citations',
    objectiveLabel: 'What should I explain simply?',
    objectivePlaceholder: 'e.g. Explain our billing logic simply',
    exampleOutcomes: ['Simple core', 'Built-up detail', 'Citations'],
  },
  {
    id: 'learning-path',
    name: 'Learning Path Planner',
    category: 'learning',
    icon: 'activity',
    accent: '#2dd4bf',
    tagline: 'Sequences what to learn from what you already have.',
    does: 'order the topics the vault covers into a sensible learning path, noting prerequisites and what is missing',
    objectiveLabel: 'What should I plan a path for?',
    objectivePlaceholder: 'e.g. Plan how to learn our codebase',
    exampleOutcomes: ['Ordered path', 'Prerequisites', 'Gaps to fill'],
  },
  {
    id: 'key-takeaways',
    name: 'Key Takeaways',
    category: 'learning',
    icon: 'pen-line',
    accent: '#2dd4bf',
    tagline: 'Pulls the must-remember points from any material.',
    does: 'distill the referenced material into a short list of the most important points to remember, each tied to its source',
    objectiveLabel: 'What should I pull takeaways from?',
    objectivePlaceholder: 'e.g. Key takeaways from the strategy offsite notes',
    exampleOutcomes: ['Must-remember points', 'Why they matter', 'Sources'],
  },
  {
    id: 'misconception-checker',
    name: 'Misconception Checker',
    category: 'learning',
    icon: 'search',
    accent: '#2dd4bf',
    tagline: 'Tests your understanding against your own notes.',
    does: 'compare the understanding you describe against what the vault actually says and gently correct any mismatch, with citations',
    objectiveLabel: 'What understanding should I check?',
    objectivePlaceholder: 'e.g. Check my understanding of the refund flow',
    exampleOutcomes: ['Confirmed points', 'Corrections', 'Citations'],
  },
]

// ── Assembled library ─────────────────────────────────────────────────────────
export const SKILL_LIBRARY_SPECS: SkillSpec[] = [
  ...RESEARCH_SPECS,
  ...SALES_SPECS,
  ...PRODUCTIVITY_SPECS,
  ...OPS_SPECS,
  ...CONTENT_SPECS,
  ...KNOWLEDGE_SPECS,
  ...PLANNING_SPECS,
  ...COMMUNICATION_SPECS,
  ...FINANCE_SPECS,
  ...ENGINEERING_SPECS,
  ...MARKETING_SPECS,
  ...PEOPLE_SPECS,
  ...LEGAL_SPECS,
  ...PERSONAL_SPECS,
  ...LEARNING_SPECS,
]
